# Site wide configuration

title: Familia Sana
description: "Familia Sana"
logo: 120x120.png
teaser: 400x250.jpg
locale: en_US
url: //familiasana.info
disqus-shortname: siemprecreciendo
image:
  folder: 20141105


# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: FamiliaSanaWDNica
  web: http://familiasana.info
  email: admin@familiasana.info
  twitter: wfamiliasana
#  bio: "Just another boring, tattooed, time traveling designer."
#  avatar: bio-photo.jpg # 160x160 px image for author byline
  # google:
  #   plus: +WDNicaWebDesignNica
  #   ad-client: ca-pub-2974536034521527
  #   ad-slot: 2949192090


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]

theme: jekyll-theme-cayman